apigee_project_id               = "aviato-andy-apigee-tf-zh"
hub_project_id                  = "aviato-andy-apigee-tf-zh"
region                          = "australia-southeast1"
service_networking_peering_cidr = "10.21.0.0/20"
environment                     = "dev"